apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ${{ values.name }} 
  name: ${{ values.name }}
spec:
  ports:
  - port: ${{ values.appPort }}
    protocol: TCP
    targetPort: ${{ values.appPort }}
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: ${{ values.name }} 
